-- Malaysian universities, polytechnics, and colleges
-- level = 'tertiary' for all entries

INSERT INTO public.schools (name, type, level, state, district, city) VALUES

-- ══════════════ UNIVERSITI AWAM (Public Universities) ══════════════
('Universiti Malaya (UM)','Universiti Awam','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('Universiti Kebangsaan Malaysia (UKM)','Universiti Awam','tertiary','Selangor','Hulu Langat','Bangi'),
('Universiti Putra Malaysia (UPM)','Universiti Awam','tertiary','Selangor','Seri Kembangan','Serdang'),
('Universiti Teknologi Malaysia (UTM)','Universiti Awam','tertiary','Johor','Johor Bahru','Skudai'),
('Universiti Sains Malaysia (USM)','Universiti Awam','tertiary','Pulau Pinang','Timur Laut','Minden'),
('Universiti Teknologi MARA (UiTM) Shah Alam','Universiti Awam','tertiary','Selangor','Petaling','Shah Alam'),
('Universiti Teknologi MARA (UiTM) Puncak Alam','Universiti Awam','tertiary','Selangor','Kuala Selangor','Puncak Alam'),
('Universiti Teknologi MARA (UiTM) Dungun','Universiti Awam','tertiary','Terengganu','Dungun','Dungun'),
('Universiti Teknologi MARA (UiTM) Kota Samarahan','Universiti Awam','tertiary','Sarawak','Samarahan','Kota Samarahan'),
('Universiti Teknologi MARA (UiTM) Kota Kinabalu','Universiti Awam','tertiary','Sabah','Kota Belud','Kota Kinabalu'),
('Universiti Malaysia Sarawak (UNIMAS)','Universiti Awam','tertiary','Sarawak','Samarahan','Kota Samarahan'),
('Universiti Malaysia Sabah (UMS)','Universiti Awam','tertiary','Sabah','Kota Belud','Kota Kinabalu'),
('Universiti Malaysia Pahang Al-Sultan Abdullah (UMPSA)','Universiti Awam','tertiary','Pahang','Kuantan','Gambang'),
('Universiti Pendidikan Sultan Idris (UPSI)','Universiti Awam','tertiary','Perak','Batang Padang','Tanjung Malim'),
('Universiti Malaysia Terengganu (UMT)','Universiti Awam','tertiary','Terengganu','Kuala Nerus','Kuala Nerus'),
('Universiti Malaysia Kelantan (UMK)','Universiti Awam','tertiary','Kelantan','Kota Bharu','Kota Bharu'),
('Universiti Teknikal Malaysia Melaka (UTeM)','Universiti Awam','tertiary','Melaka','Alor Gajah','Durian Tunggal'),
('Universiti Tun Hussein Onn Malaysia (UTHM)','Universiti Awam','tertiary','Johor','Batu Pahat','Parit Raja'),
('Universiti Malaysia Perlis (UniMAP)','Universiti Awam','tertiary','Perlis','Arau','Arau'),
('Universiti Sultan Zainal Abidin (UniSZA)','Universiti Awam','tertiary','Terengganu','Kuala Nerus','Kuala Terengganu'),
('Universiti Islam Antarabangsa Malaysia (UIAM / IIUM)','Universiti Awam','tertiary','Selangor','Gombak','Gombak'),
('Universiti Sains Islam Malaysia (USIM)','Universiti Awam','tertiary','Negeri Sembilan','Nilai','Nilai'),
('Universiti Utara Malaysia (UUM)','Universiti Awam','tertiary','Kedah','Kubang Pasu','Sintok'),
('Universiti Malaysia Sabah Kampus Antarabangsa Labuan (UMS-KAL)','Universiti Awam','tertiary','Labuan','Labuan','Labuan'),
('Universiti Pertahanan Nasional Malaysia (UPNM)','Universiti Awam','tertiary','Kuala Lumpur','Kuala Lumpur','Sungai Besi'),

-- ══════════════ UNIVERSITI SWASTA (Private Universities) ══════════════
('Taylor''s University','Universiti Swasta','tertiary','Selangor','Petaling','Subang Jaya'),
('Sunway University','Universiti Swasta','tertiary','Selangor','Petaling','Bandar Sunway'),
('UCSI University','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('HELP University','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Bukit Damansara'),
('Asia Pacific University (APU)','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Technology Park Malaysia'),
('Multimedia University (MMU) Cyberjaya','Universiti Swasta','tertiary','Selangor','Sepang','Cyberjaya'),
('Multimedia University (MMU) Melaka','Universiti Swasta','tertiary','Melaka','Melaka Tengah','Melaka'),
('University of Nottingham Malaysia','Universiti Swasta','tertiary','Selangor','Hulu Langat','Semenyih'),
('Monash University Malaysia','Universiti Swasta','tertiary','Selangor','Petaling','Bandar Sunway'),
('Curtin University Malaysia','Universiti Swasta','tertiary','Sarawak','Miri','Miri'),
('Heriot-Watt University Malaysia','Universiti Swasta','tertiary','Putrajaya','Putrajaya','Putrajaya'),
('Newcastle University Medicine Malaysia (NUMed)','Universiti Swasta','tertiary','Johor','Johor Bahru','Iskandar Puteri'),
('International Medical University (IMU)','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Bukit Jalil'),
('Management and Science University (MSU)','Universiti Swasta','tertiary','Selangor','Petaling','Shah Alam'),
('Universiti Tenaga Nasional (UNITEN)','Universiti Swasta','tertiary','Selangor','Hulu Langat','Kajang'),
('SEGi University','Universiti Swasta','tertiary','Selangor','Petaling','Kota Damansara'),
('INTI International University','Universiti Swasta','tertiary','Negeri Sembilan','Nilai','Nilai'),
('KDU University College','Universiti Swasta','tertiary','Selangor','Petaling','Utama'),
('Universiti Tun Abdul Razak (UNIRAZAK)','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','KLCC'),
('Limkokwing University of Creative Technology','Universiti Swasta','tertiary','Selangor','Sepang','Cyberjaya'),
('Lincoln University College','Universiti Swasta','tertiary','Selangor','Petaling','Petaling Jaya'),
('Binary University','Universiti Swasta','tertiary','Selangor','Petaling','Puchong'),
('City University Malaysia','Universiti Swasta','tertiary','Selangor','Petaling','Petaling Jaya'),
('Universiti Kuala Lumpur (UniKL)','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('Masterskill University College of Health Sciences (MUCH)','Universiti Swasta','tertiary','Selangor','Hulu Langat','Cheras'),

-- ══════════════ POLITEKNIK ══════════════
('Politeknik Sultan Salahuddin Abdul Aziz Shah','Politeknik','tertiary','Selangor','Petaling','Shah Alam'),
('Politeknik Ungku Omar','Politeknik','tertiary','Perak','Kinta','Ipoh'),
('Politeknik Sultan Haji Ahmad Shah','Politeknik','tertiary','Pahang','Kuantan','Semambu'),
('Politeknik Kuching Sarawak','Politeknik','tertiary','Sarawak','Kuching','Kuching'),
('Politeknik Kota Kinabalu','Politeknik','tertiary','Sabah','Kota Kinabalu','Kota Kinabalu'),
('Politeknik Johor Bahru','Politeknik','tertiary','Johor','Johor Bahru','Johor Bahru'),
('Politeknik Seberang Perai','Politeknik','tertiary','Pulau Pinang','Seberang Perai Tengah','Seberang Perai'),
('Politeknik Kota Bharu','Politeknik','tertiary','Kelantan','Kota Bharu','Kota Bharu'),
('Politeknik Kuala Terengganu','Politeknik','tertiary','Terengganu','Kuala Terengganu','Kuala Terengganu'),
('Politeknik Tuanku Sultanah Bahiyah','Politeknik','tertiary','Kedah','Kulim','Kulim'),
('Politeknik Port Dickson','Politeknik','tertiary','Negeri Sembilan','Port Dickson','Port Dickson'),
('Politeknik Merlimau','Politeknik','tertiary','Melaka','Jasin','Merlimau'),
('Politeknik Mersing','Politeknik','tertiary','Johor','Mersing','Mersing'),

-- ══════════════ KOLEJ KOMUNITI ══════════════
('Kolej Komuniti Kuala Lumpur','Kolej Komuniti','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('Kolej Komuniti Selayang','Kolej Komuniti','tertiary','Selangor','Gombak','Selayang'),
('Kolej Komuniti Petaling Jaya','Kolej Komuniti','tertiary','Selangor','Petaling','Petaling Jaya'),
('Kolej Komuniti Hulu Langat','Kolej Komuniti','tertiary','Selangor','Hulu Langat','Ampang'),
('Kolej Komuniti Johor Bahru','Kolej Komuniti','tertiary','Johor','Johor Bahru','Johor Bahru'),
('Kolej Komuniti Ipoh','Kolej Komuniti','tertiary','Perak','Kinta','Ipoh'),
('Kolej Komuniti Penang','Kolej Komuniti','tertiary','Pulau Pinang','Timur Laut','George Town'),
('Kolej Komuniti Alor Setar','Kolej Komuniti','tertiary','Kedah','Kota Setar','Alor Setar'),
('Kolej Komuniti Kuantan','Kolej Komuniti','tertiary','Pahang','Kuantan','Kuantan'),
('Kolej Komuniti Kota Bharu','Kolej Komuniti','tertiary','Kelantan','Kota Bharu','Kota Bharu'),

-- ══════════════ KOLEJ MATRIKULASI ══════════════
('Kolej Matrikulasi Johor','Kolej Matrikulasi','tertiary','Johor','Tangkak','Tangkak'),
('Kolej Matrikulasi Melaka','Kolej Matrikulasi','tertiary','Melaka','Alor Gajah','Lendu'),
('Kolej Matrikulasi Negeri Sembilan','Kolej Matrikulasi','tertiary','Negeri Sembilan','Rembau','Rembau'),
('Kolej Matrikulasi Selangor','Kolej Matrikulasi','tertiary','Selangor','Gombak','Batu Caves'),
('Kolej Matrikulasi Perak','Kolej Matrikulasi','tertiary','Perak','Manjung','Pengkalan Baharu'),
('Kolej Matrikulasi Pulau Pinang','Kolej Matrikulasi','tertiary','Pulau Pinang','Seberang Perai Tengah','Kepala Batas'),
('Kolej Matrikulasi Kedah','Kolej Matrikulasi','tertiary','Kedah','Kota Setar','Jitra'),
('Kolej Matrikulasi Pahang','Kolej Matrikulasi','tertiary','Pahang','Pekan','Pekan'),
('Kolej Matrikulasi Terengganu','Kolej Matrikulasi','tertiary','Terengganu','Kuala Nerus','Kuala Terengganu'),
('Kolej Matrikulasi Kelantan','Kolej Matrikulasi','tertiary','Kelantan','Kota Bharu','Kota Bharu'),
('Kolej Matrikulasi Sabah','Kolej Matrikulasi','tertiary','Sabah','Kota Belud','Kota Kinabalu'),
('Kolej Matrikulasi Sarawak','Kolej Matrikulasi','tertiary','Sarawak','Kuching','Kuching'),
('Kolej Matrikulasi Labuan','Kolej Matrikulasi','tertiary','Labuan','Labuan','Labuan'),
('Kolej Matrikulasi Perlis','Kolej Matrikulasi','tertiary','Perlis','Arau','Arau');
