-- Additional Malaysian institutions of higher learning (IHL)
-- Expands coverage: more private universities, polytechnics, university colleges

INSERT INTO public.schools (name, type, level, state, district, city) VALUES

-- ══════════════ ADDITIONAL UNIVERSITI AWAM campuses ══════════════
('Universiti Teknologi MARA (UiTM) Johor','Universiti Awam','tertiary','Johor','Segamat','Segamat'),
('Universiti Teknologi MARA (UiTM) Kedah','Universiti Awam','tertiary','Kedah','Sik','Merbok'),
('Universiti Teknologi MARA (UiTM) Kelantan','Universiti Awam','tertiary','Kelantan','Machang','Machang'),
('Universiti Teknologi MARA (UiTM) Melaka','Universiti Awam','tertiary','Melaka','Alor Gajah','Alor Gajah'),
('Universiti Teknologi MARA (UiTM) Negeri Sembilan','Universiti Awam','tertiary','Negeri Sembilan','Kuala Pilah','Kuala Pilah'),
('Universiti Teknologi MARA (UiTM) Pahang','Universiti Awam','tertiary','Pahang','Jengka','Jengka'),
('Universiti Teknologi MARA (UiTM) Perak','Universiti Awam','tertiary','Perak','Manjung','Seri Iskandar'),
('Universiti Teknologi MARA (UiTM) Perlis','Universiti Awam','tertiary','Perlis','Arau','Arau'),
('Universiti Teknologi MARA (UiTM) Pulau Pinang','Universiti Awam','tertiary','Pulau Pinang','Seberang Perai Tengah','Bukit Mertajam'),
('Universiti Teknologi MARA (UiTM) Terengganu','Universiti Awam','tertiary','Terengganu','Dungun','Dungun'),
('Universiti Teknologi MARA (UiTM) Sabah','Universiti Awam','tertiary','Sabah','Kota Kinabalu','Kota Kinabalu'),
('Universiti Teknologi MARA (UiTM) Kuching','Universiti Awam','tertiary','Sarawak','Kuching','Kuching'),
('Universiti Putra Malaysia Bintulu Campus','Universiti Awam','tertiary','Sarawak','Bintulu','Bintulu'),
('UTM Kuala Lumpur (International Campus)','Universiti Awam','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('USM Kampus Kejuruteraan','Universiti Awam','tertiary','Pulau Pinang','Seberang Perai Selatan','Nibong Tebal'),
('USM Kampus Kesihatan','Universiti Awam','tertiary','Kelantan','Kota Bharu','Kubang Kerian'),

-- ══════════════ ADDITIONAL UNIVERSITI SWASTA ══════════════
('Universiti Tunku Abdul Rahman (UTAR) Sungai Long','Universiti Swasta','tertiary','Selangor','Hulu Langat','Sungai Long'),
('Universiti Tunku Abdul Rahman (UTAR) Kampar','Universiti Swasta','tertiary','Perak','Kampar','Kampar'),
('Open University Malaysia (OUM)','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('Wawasan Open University (WOU)','Universiti Swasta','tertiary','Pulau Pinang','Timur Laut','George Town'),
('MAHSA University','Universiti Swasta','tertiary','Selangor','Petaling','Jenjarum'),
('AIMST University','Universiti Swasta','tertiary','Kedah','Kulim','Bedong'),
('Quest International University','Universiti Swasta','tertiary','Perak','Ipoh','Ipoh'),
('Universiti Selangor (UNISEL)','Universiti Swasta','tertiary','Selangor','Batang Berjuntai','Bestari Jaya'),
('Infrastructure University Kuala Lumpur (IUKL)','Universiti Swasta','tertiary','Selangor','Hulu Langat','Kajang'),
('Nilai University','Universiti Swasta','tertiary','Negeri Sembilan','Nilai','Nilai'),
('Asia Metropolitan University (AMU)','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Cheras'),
('Berjaya University College','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('Xiamen University Malaysia Campus (XMUMC)','Universiti Swasta','tertiary','Selangor','Sepang','Sepang'),
('Albukhary International University','Universiti Swasta','tertiary','Kedah','Alor Setar','Alor Setar'),
('UNITAR International University','Universiti Swasta','tertiary','Selangor','Petaling','Petaling Jaya'),
('DRB-HICOM University of Automotive Malaysia (DHU)','Universiti Swasta','tertiary','Pahang','Pekan','Pekan'),
('Southern University College','Universiti Swasta','tertiary','Johor','Johor Bahru','Skudai'),
('New Era University College','Universiti Swasta','tertiary','Selangor','Hulu Langat','Kajang'),
('Han Chiang University College of Communication','Universiti Swasta','tertiary','Pulau Pinang','Timur Laut','George Town'),
('Tunku Abdul Rahman University of Management & Technology (TAR UMT)','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Setapak'),
('KPJ Healthcare University','Universiti Swasta','tertiary','Negeri Sembilan','Nilai','Nilai'),
('University of Reading Malaysia','Universiti Swasta','tertiary','Johor','Johor Bahru','Iskandar Puteri'),
('EduCity Iskandar Malaysia (Newcastle, etc.)','Universiti Swasta','tertiary','Johor','Johor Bahru','Iskandar Puteri'),
('SEGI University Kota Damansara','Universiti Swasta','tertiary','Selangor','Petaling','Kota Damansara'),
('SEGI University Kuala Lumpur','Universiti Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('SEGI University Penang','Universiti Swasta','tertiary','Pulau Pinang','Timur Laut','George Town'),
('SEGI University Subang','Universiti Swasta','tertiary','Selangor','Petaling','Subang Jaya'),
('INTI International University Nilai','Universiti Swasta','tertiary','Negeri Sembilan','Nilai','Nilai'),
('INTI International College Subang','Universiti Swasta','tertiary','Selangor','Petaling','Subang Jaya'),
('INTI International College Penang','Universiti Swasta','tertiary','Pulau Pinang','Timur Laut','George Town'),
('Taylor''s College Subang Jaya','Universiti Swasta','tertiary','Selangor','Petaling','Subang Jaya'),
('Sunway College','Universiti Swasta','tertiary','Selangor','Petaling','Bandar Sunway'),

-- ══════════════ ADDITIONAL POLITEKNIK ══════════════
('Politeknik Ibrahim Sultan','Politeknik','tertiary','Johor','Johor Bahru','Pasir Gudang'),
('Politeknik Kluang','Politeknik','tertiary','Johor','Kluang','Kluang'),
('Politeknik Balik Pulau','Politeknik','tertiary','Pulau Pinang','Barat Daya','Balik Pulau'),
('Politeknik Nilai','Politeknik','tertiary','Negeri Sembilan','Nilai','Nilai'),
('Politeknik Banting','Politeknik','tertiary','Selangor','Kuala Langat','Banting'),
('Politeknik Sultan Mizan Zainal Abidin','Politeknik','tertiary','Terengganu','Besut','Besut'),
('Politeknik Hulu Terengganu','Politeknik','tertiary','Terengganu','Hulu Terengganu','Kuala Berang'),
('Politeknik Muadzam Shah','Politeknik','tertiary','Pahang','Rompin','Muadzam Shah'),
('Politeknik Sandakan','Politeknik','tertiary','Sabah','Sandakan','Sandakan'),
('Politeknik Kuching Sarawak (Metro)','Politeknik','tertiary','Sarawak','Kuching','Kuching'),
('Politeknik Metro Johor Bahru','Politeknik','tertiary','Johor','Johor Bahru','Johor Bahru'),
('Politeknik Metro Kuala Lumpur','Politeknik','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('Politeknik Metro Betong','Politeknik','tertiary','Sarawak','Betong','Betong'),
('Politeknik Tuanku Syed Sirajuddin','Politeknik','tertiary','Perlis','Arau','Arau'),
('Politeknik Tuanku Sultanah Bahiyah (PTSB)','Politeknik','tertiary','Kedah','Kulim','Kulim'),
('Politeknik Merlimau Melaka','Politeknik','tertiary','Melaka','Jasin','Merlimau'),
('Politeknik Jeli Kelantan','Politeknik','tertiary','Kelantan','Jeli','Jeli'),
('Politeknik Mukah','Politeknik','tertiary','Sarawak','Mukah','Mukah'),
('Politeknik Tawau','Politeknik','tertiary','Sabah','Tawau','Tawau'),

-- ══════════════ KOLEJ UNIVERSITI (University Colleges) ══════════════
('Kolej Universiti Islam Antarabangsa Selangor (KUIS)','Kolej Swasta','tertiary','Selangor','Kajang','Kajang'),
('Kolej Universiti Islam Selangor (KUIS)','Kolej Swasta','tertiary','Selangor','Hulu Langat','Kajang'),
('Kolej Universiti Poly-Tech MARA (KUPTM)','Kolej Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur'),
('Kolej Universiti Perguruan Ugama Seri Begawan','Kolej Swasta','tertiary','Selangor','Petaling','Petaling Jaya'),
('Kolej Yayasan Saad','Kolej Swasta','tertiary','Melaka','Melaka Tengah','Melaka'),
('Kolej Teknologi Timur','Kolej Swasta','tertiary','Selangor','Sepang','Sepang'),
('Kolej Islam Teknologi Antarabangsa Pulau Pinang (KITAB)','Kolej Swasta','tertiary','Pulau Pinang','Timur Laut','George Town'),
('Tunku Abdul Rahman College (TARC) Kuala Lumpur','Kolej Swasta','tertiary','Kuala Lumpur','Kuala Lumpur','Setapak'),
('Tunku Abdul Rahman College (TARC) Penang','Kolej Swasta','tertiary','Pulau Pinang','Timur Laut','George Town'),
('Tunku Abdul Rahman College (TARC) Johor Bahru','Kolej Swasta','tertiary','Johor','Johor Bahru','Johor Bahru'),
('Tunku Abdul Rahman College (TARC) Sabah','Kolej Swasta','tertiary','Sabah','Kota Kinabalu','Kota Kinabalu'),
('Tunku Abdul Rahman College (TARC) Sarawak','Kolej Swasta','tertiary','Sarawak','Kuching','Kuching'),

-- ══════════════ ADDITIONAL KOLEJ KOMUNITI ══════════════
('Kolej Komuniti Seremban','Kolej Komuniti','tertiary','Negeri Sembilan','Seremban','Seremban'),
('Kolej Komuniti Ledang','Kolej Komuniti','tertiary','Johor','Ledang','Ledang'),
('Kolej Komuniti Batu Pahat','Kolej Komuniti','tertiary','Johor','Batu Pahat','Batu Pahat'),
('Kolej Komuniti Kulim','Kolej Komuniti','tertiary','Kedah','Kulim','Kulim'),
('Kolej Komuniti Langkawi','Kolej Komuniti','tertiary','Kedah','Langkawi','Kuah'),
('Kolej Komuniti Kuala Kangsar','Kolej Komuniti','tertiary','Perak','Kuala Kangsar','Kuala Kangsar'),
('Kolej Komuniti Teluk Intan','Kolej Komuniti','tertiary','Perak','Hilir Perak','Teluk Intan'),
('Kolej Komuniti Segamat','Kolej Komuniti','tertiary','Johor','Segamat','Segamat'),
('Kolej Komuniti Arau','Kolej Komuniti','tertiary','Perlis','Arau','Arau'),
('Kolej Komuniti Kuching','Kolej Komuniti','tertiary','Sarawak','Kuching','Kuching'),
('Kolej Komuniti Miri','Kolej Komuniti','tertiary','Sarawak','Miri','Miri'),
('Kolej Komuniti Lahad Datu','Kolej Komuniti','tertiary','Sabah','Lahad Datu','Lahad Datu'),
('Kolej Komuniti Tawau','Kolej Komuniti','tertiary','Sabah','Tawau','Tawau'),
('Kolej Komuniti Sandakan','Kolej Komuniti','tertiary','Sabah','Sandakan','Sandakan');
